spring.application.name=finalprojec
spring.jpa.hibernate.ddl-auto=update
spring.datasource.name=tradedocument
spring.datasource.url=jdbc:mysql://localhost:3306/tfms
spring.datasource.username=root
spring.datasource.password=Catssrikakulam@4321
server.port=8083

spring.jpa.show-sql=true
